# Generated by Django 5.1.6 on 2025-03-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_loan_id_paymentschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(default='F6433A5026', max_length=20, unique=True),
        ),
    ]
