# Generated by Django 5.1.6 on 2025-03-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_user_alter_loan_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
